In [1]:

import pandas as pd
import numpy as np

data = {
    "Product_ID": [
        201, 202, 203, 204, 205,
        206, 207, 208, 209, 210,
        211, 212, 213, 214, 215,
        216, 217, 218, 219, 201
    ],

    "Item_Name": [
        "Surgical Gloves", "Face Masks", "Digital Thermometer",
        "Blood Pressure Monitor", "Hand Sanitizer",
        "Syringe", "Stethoscope", "Surgical Gloves",
        "Pulse Oximeter", "Face Masks",
        "Wheelchair", "Digital Thermometer",
        "First Aid Kit", "Infrared Thermometer",
        "Hand Sanitizer", "Nebulizer", "Surgical Gown",
        "Oxygen Cylinder", "ECG Machine", "Surgical Gloves"
    ],

    "Category": [
        "Consumables", "Consumables", "Diagnostic",
        "Monitoring", "Consumables", "Consumables",
        "Diagnostic", "Consumables", "Monitoring",
        "Consumables", "Mobility", "Diagnostic",
        "Emergency", "Diagnostic", "Consumables",
        "Respiratory", "Consumables", "Respiratory",
        "Diagnostic", "Consumables"
    ],

    "Supplier": [
        "MedSupply A", "MedSupply B", "HealthTech",
        "HealthTech", "MedSupply A", "MedSupply B",
        "HealthTech", "MedSupply A", None, "MedSupply B",
        "MobilityCare", "HealthTech", "MedSupply A",
        "HealthTech", "MedSupply A", "RespiraCare",
        "MedSupply B", "RespiraCare", "HealthTech",
        "MedSupply A"
    ],

    "Unit_Price": [
        250, 100, 850, 4500, 300,
        25, 1200, 250, 1800, np.nan,
        15000, 850, 750, 2200, 300,
        3500, 900, 999999, 45000, 250
    ],

    "Units_Sold": [
        100, 500, 30, 15, 80,
        1000, 25, 100, 40, 450,
        5, 35, 20, 25, 80,
        18, 60, 3, 4, 100
    ],

    "Stock": [
        500, 1200, 40, 20, np.nan,
        3000, 35, 500, 60, 800,
        8, 50, 30, 40, 200,
        25, 100, 6, 5, 500
    ]
}

df = pd.DataFrame(data)

In [2]:
df

,Product_ID,Item_Name,Category,Supplier,Unit_Price,Units_Sold,Stock
0,201,Surgical Gloves,Consumables,MedSupply A,250.0,100,500.0
1,202,Face Masks,Consumables,MedSupply B,100.0,500,1200.0
2,203,Digital Thermometer,Diagnostic,HealthTech,850.0,30,40.0
3,204,Blood Pressure Monitor,Monitoring,HealthTech,4500.0,15,20.0
4,205,Hand Sanitizer,Consumables,MedSupply A,300.0,80,NaN
5,206,Syringe,Consumables,MedSupply B,25.0,1000,3000.0
6,207,Stethoscope,Diagnostic,HealthTech,1200.0,25,35.0
7,208,Surgical Gloves,Consumables,MedSupply A,250.0,100,500.0
8,209,Pulse Oximeter,Monitoring,NaN,1800.0,40,60.0
9,210,Face Masks,Consumables,MedSupply B,NaN,450,800.0
10,211,Wheelchair,Mobility,MobilityCare,15000.0,5,8.0
11,212,Digital Thermometer,Diagnostic,HealthTech,850.0,35,50.0
12,213,First Aid Kit,Emergency,MedSupply A,750.0,20,30.0
13,214,Infrared Thermometer,Diagnostic,HealthTech,2200.0,25,40.0
14,215,Hand Sanitizer,Consumables,MedSupply A,300.0,80,200.0
15,216,Nebulizer,Respiratory,RespiraCare,3500.0,18,25.0
16,217,Surgical Gown,Consumables,MedSupply B,900.0,60,100.0
17,218,Oxygen Cylinder,Respiratory,RespiraCare,999999.0,3,6.0
18,219,ECG Machine,Diagnostic,HealthTech,45000.0,4,5.0
19,201,Surgical Gloves,Consumables,MedSupply A,250.0,100,500.0

In [3]:
df.isna().sum()

Product_ID    0
Item_Name     0
Category      0
Supplier      1
Unit_Price    1
Units_Sold    0
Stock         1
dtype: int64

In [6]:
df.isnull().sum()

Product_ID    0
Item_Name     0
Category      0
Supplier      1
Unit_Price    1
Units_Sold    0
Stock         1
dtype: int64

In [7]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19     True
dtype: bool

In [8]:
df.duplicated().sum()

np.int64(1)

In [9]:
df[df.duplicated()]

,Product_ID,Item_Name,Category,Supplier,Unit_Price,Units_Sold,Stock
19,201,Surgical Gloves,Consumables,MedSupply A,250.0,100,500.0

In [11]:
df_clean = df.drop_duplicates().copy()

In [13]:
df_clean["Sales_Value"] = (df_clean["Unit_Price"] * df_clean["Units_Sold"])

In [14]:
df_clean.groupby("Category")["Sales_Value"].sum()

Category
Consumables     227000.0
Diagnostic      320250.0
Emergency        15000.0
Mobility         75000.0
Monitoring      139500.0
Respiratory    3062997.0
Name: Sales_Value, dtype: float64

In [17]:
df_clean.head()

,Product_ID,Item_Name,Category,Supplier,Unit_Price,Units_Sold,Stock,Sales_Value
0,201,Surgical Gloves,Consumables,MedSupply A,250.0,100,500.0,25000.0
1,202,Face Masks,Consumables,MedSupply B,100.0,500,1200.0,50000.0
2,203,Digital Thermometer,Diagnostic,HealthTech,850.0,30,40.0,25500.0
3,204,Blood Pressure Monitor,Monitoring,HealthTech,4500.0,15,20.0,67500.0
4,205,Hand Sanitizer,Consumables,MedSupply A,300.0,80,NaN,24000.0

In [19]:
df_clean.tail(3)

,Product_ID,Item_Name,Category,Supplier,Unit_Price,Units_Sold,Stock,Sales_Value
16,217,Surgical Gown,Consumables,MedSupply B,900.0,60,100.0,54000.0
17,218,Oxygen Cylinder,Respiratory,RespiraCare,999999.0,3,6.0,2999997.0
18,219,ECG Machine,Diagnostic,HealthTech,45000.0,4,5.0,180000.0

In [20]:
highest_price=df["Unit_Price"].max()

In [21]:
highest_price

np.float64(999999.0)